# Generated by Django 4.1.7 on 2023-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supergood_reads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="release_year",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
