# Generated by Django 4.2.3 on 2023-09-03 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("supergood_reads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_limit",
                    models.IntegerField(blank=True, default=100, null=True),
                ),
                (
                    "media_item_limit",
                    models.IntegerField(blank=True, default=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="media_item_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_item_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.DeleteModel(
            name="UserReviewStrategyDefault",
        ),
    ]
