# Generated by Django 4.2.3 on 2023-09-16 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("supergood_reads", "0003_rename_great_film_ebertstrategy_goat"),
    ]

    operations = [
        migrations.CreateModel(
            name="TomatoStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fresh", models.BooleanField()),
            ],
            options={
                "verbose_name": "Tomatoes",
            },
        ),
        migrations.RenameModel(
            old_name="MaximusStrategy",
            new_name="ThumbsStrategy",
        ),
        migrations.AlterModelOptions(
            name="imdbstrategy",
            options={"verbose_name": "IMDB"},
        ),
        migrations.AlterModelOptions(
            name="letterboxdstrategy",
            options={"verbose_name": "Letterboxd"},
        ),
        migrations.AlterModelOptions(
            name="thumbsstrategy",
            options={"verbose_name": "Thumbs"},
        ),
    ]
