# Generated by Django 4.2.3 on 2023-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supergood_reads", "0005_rename_user_review_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publication_year",
            new_name="year",
        ),
        migrations.RenameField(
            model_name="film",
            old_name="release_year",
            new_name="year",
        ),
        migrations.AddField(
            model_name="book",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="film",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="demo",
            field=models.BooleanField(default=False),
        ),
    ]
