# Generated by Django 4.2.3 on 2023-08-22 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supergood_reads", "0006_rename_publication_year_book_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genre",
            new_name="name",
        ),
    ]
