version: '3.9'

services:
  db:
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: postgres:14.1
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    command: -p ${POSTGRES_PORT}

  app:
    environment:
      - PORT
      - HOST
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DEBUG
      - SECRET_KEY
    image: '${COMPOSE_PROJECT_NAME}-app:${DOCKER_APP_IMAGE_TAG:-local-latest}'
    build:
      context: ../../..
      dockerfile: ./deploy/docker/images/django/django.Dockerfile
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    links:
      - db:postgres
