# Generated by Django 4.2.3 on 2023-07-17 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "supergood_review_site",
            "0002_alter_book_publication_year_alter_film_release_year",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="release_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="media_type_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_type_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="media_type_object_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="strategy_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategy_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="strategy_object_id",
            field=models.UUIDField(),
        ),
    ]
