# Generated by Django 4.2.3 on 2023-07-18 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "supergood_review_site",
            "0003_alter_book_publication_year_alter_film_release_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="media_type_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_type_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="media_type_object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="strategy_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategy_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="strategy_object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
