# Generated by Django 4.1.5 on 2023-01-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_flex_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="media_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="media_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="strategy_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategy_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="strategy_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
