# Generated by Django 4.1.3 on 2023-02-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_flex_reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=256)),
                ("director", models.CharField(default="", max_length=256)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("countries", models.ManyToManyField(to="django_flex_reviews.country")),
                ("genres", models.ManyToManyField(to="django_flex_reviews.genre")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=256)),
                ("author", models.CharField(default="", max_length=256)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("genres", models.ManyToManyField(to="django_flex_reviews.genre")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
