# Generated by Django 4.1.6 on 2023-02-15 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_flex_reviews", "0002_country_genre_film_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ebertstrategy",
            options={"verbose_name": "Ebert"},
        ),
    ]
