# Generated by Django 4.1.6 on 2023-02-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_flex_reviews", "0003_alter_ebertstrategy_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="django_flex_media_c_1d0af3_idx",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="media_object_id",
            new_name="media_type_object_id",
        ),
        migrations.RemoveField(
            model_name="review",
            name="media_content_type",
        ),
        migrations.AddField(
            model_name="review",
            name="media_type_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_type_review_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["media_type_content_type", "media_type_object_id"],
                name="django_flex_media_t_26d8c1_idx",
            ),
        ),
    ]
