# Generated by Django 4.1.7 on 2023-03-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_flex_reviews",
            "0005_alter_book_id_alter_ebertstrategy_id_alter_film_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Book"},
        ),
        migrations.AlterModelOptions(
            name="film",
            options={"verbose_name": "Film"},
        ),
        migrations.AlterModelOptions(
            name="goodreadsstrategy",
            options={"verbose_name": "Goodreads"},
        ),
        migrations.AlterModelOptions(
            name="maximusstrategy",
            options={"verbose_name": "Maximus"},
        ),
        migrations.RemoveField(
            model_name="country",
            name="country",
        ),
        migrations.AddField(
            model_name="country",
            name="name",
            field=models.CharField(default="", max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
